diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user..email=euaggeliony28@gmail.com
user.email=bmc.webdevelop@gmail.com
user.name=Yearico Vio Euaggelion
user.email==
user.email=euaggeliony28@gmail.com
gui.recentrepo=C:/Users/User/Dropbox/artikel
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/YVE20/sionWKO.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
